### ISSUE TITLE
Improve documentation - small changes

### ISSUE THREAD

**Issue by nevencaplar** [lincc-frameworks/tape#372]
List of smaller change to the documentation 

### tasks
- [x] Home page should not have Dev Guide - Getting Started; Just overview of the sections and a lot of links (to sections, LSST and such) - more like this (https://docs.lightkurve.org/tutorials/index.html#)
- [x] Modify recommended python 3.10 to 3.11 `>> conda create env -n <env_name> python=3.10 -> 3.11`
- [x] In Section https://tape.readthedocs.io/en/latest/tutorials/working_with_the_ensemble.html#Inspection
Fix incomplete sentence ``This allows you to supply a given object ID, and returns a TimeSeries object (see ).''
- [x] In same location, add a sentence such as ``Note that this loads the data from all available bands’’
- [x] Quickstart - again mentioning installation, with the same wording as in ``Installing TAPE’’.  Change wording
- [ ] `Ensemble.sample` - mention that one can set a random seed to always get the same results
- [x] https://tape.readthedocs.io/en/latest/tutorials/working_with_the_ensemble.html#Batch-Analysis - include links to batch showcase
- [x] https://tape.readthedocs.io/en/latest/tutorials/working_with_the_ensemble.html#Updating-an-Ensemble's-Frames
(provided the input data is in multiple partitions) - link to relevant section where we show that
- [x] Better plot in[ From the ensemble](https://tape.readthedocs.io/en/latest/tutorials/working_with_the_timeseries.html#From-the-Ensemble)
- [x]  5KB mention explicitly this is not what you would use in real world (https://tape.readthedocs.io/en/latest/tutorials/scaling_to_large_data.html#Data-Partitioning-and-Parallelization)
